window.STARSHIP = {
  updated: "2026-10-09",
  note:
    "Compiled from SpaceX flight pages and public launch records. Outcomes are this desk’s read of the whole flight — not SpaceX’s official score. Flight 15 is a planning target only. Not affiliated with SpaceX.",
  next: {
    flight: 15,
    start: "2026-10-19T00:00:00Z",
    precision: "day",
    pad: "Starbase · OLP-2",
    booster: "B22",
    ship: "S42",
    block: "Block 3",
    headline: "First serious Ship catch",
    tested:
      "Planning target for the first real attempt to catch the upper stage on the tower. SpaceX has not set an official clock. Some reports have slipped the window to 8 November. Same date as the Musk-world calendar.",
  },
  flights: [
    {
      flight: 14,
      date: "2026-09-28",
      pad: "OLP-2",
      booster: "B21",
      ship: "S41",
      block: "Block 3",
      outcome: "worked",
      headline: "First orbit, 26 Starlink V3",
      tested:
        "First Starship to reach low Earth orbit and deploy an operational payload — all 26 Starlink V3 satellites. One ship engine shut down early; SpaceX still committed to orbit, then came home after three hours instead of six. Both stages made controlled splashdowns.",
    },
    {
      flight: 13,
      date: "2026-07-24",
      pad: "OLP-2",
      booster: "B20",
      ship: "S40",
      block: "Block 3",
      outcome: "partial",
      headline: "First real Starlink V3s, ship lived through tip-over",
      tested:
        "Twenty Starlink V3 satellites flew the ship’s trajectory and burned up as planned. The ship splashed down and tipped over — and survived, so SpaceX got heat-shield and engine-bay photos. Booster 20 lost engines on the landing burn and hit the Gulf hard.",
    },
    {
      flight: 12,
      date: "2026-05-22",
      pad: "OLP-2",
      booster: "B19",
      ship: "S39",
      block: "Block 3",
      outcome: "partial",
      headline: "Block 3 and Pad 2 debut",
      tested:
        "First Block 3 stack and first flight off Orbital Launch Pad 2. Ship 39 reached cutoff, deployed 20 simulators plus two modified Starlink V3s, and stuck the landing flip. Booster 19 aborted boostback after a mass engine-start failure and was lost.",
    },
    {
      flight: 11,
      date: "2025-10-13",
      pad: "OLP-1",
      booster: "B15-2",
      ship: "S38",
      block: "Block 2",
      outcome: "worked",
      headline: "Last Block 2 flight from Pad 1",
      tested:
        "Reused Booster 15 and the last Block 2 ship. Eight Starlink simulators out, in-space relight, and a clean reentry even with tiles pulled on purpose. Both stages soft-splashed. Pad 1 went into retrofit after this.",
    },
    {
      flight: 10,
      date: "2025-08-26",
      pad: "OLP-1",
      booster: "B16",
      ship: "S37",
      block: "Block 2",
      outcome: "worked",
      headline: "Simulators out, both splashdowns",
      tested:
        "Ship 36 was lost on the stand, so S37 flew late. Eight Starlink simulators deployed, a Raptor relit in space, and the ship soft-splashed within a few metres of the target despite heat damage aft. Booster splashdown after a simulated engine-out.",
    },
    {
      flight: 9,
      date: "2025-05-27",
      pad: "OLP-1",
      booster: "B14-2",
      ship: "S35",
      block: "Block 2",
      outcome: "failed",
      headline: "First reused booster — both stages lost",
      tested:
        "First Super Heavy reuse (B14’s second flight). The booster finished boostback then failed before Gulf splashdown. The ship reached cutoff, never deployed its eight simulators, leaked propellant, and broke up over the Indian Ocean.",
    },
    {
      flight: 8,
      date: "2025-03-06",
      pad: "OLP-1",
      booster: "B15-1",
      ship: "S34",
      block: "Block 2",
      outcome: "partial",
      headline: "Booster catch, second Block 2 ship lost",
      tested:
        "Another catch of a Super Heavy. Ship 34 lost engines and control during its ascent burn — the same family of failure as Flight 7. Four Starlink simulators never flew free.",
    },
    {
      flight: 7,
      date: "2025-01-16",
      pad: "OLP-1",
      booster: "B14-1",
      ship: "S33",
      block: "Block 2",
      outcome: "partial",
      headline: "First Block 2 ship — catch yes, ship no",
      tested:
        "Debut of the taller Block 2 ship and a planned 10-simulator deploy. Booster 14 was caught clean. A propellant leak killed Ship 33 about eight minutes in; the flight-termination system finished it.",
    },
    {
      flight: 6,
      date: "2024-11-19",
      pad: "OLP-1",
      booster: "B13",
      ship: "S31",
      block: "Block 1",
      outcome: "worked",
      headline: "Catch aborted, ship relight and splashdown",
      tested:
        "Last Block 1 ship. Catch called off after tower damage at liftoff; booster diverted to the Gulf. Ship 31 relit a Raptor in space and splashed down in daylight with tiles pulled on purpose. First payload: a plush banana.",
    },
    {
      flight: 5,
      date: "2024-10-13",
      pad: "OLP-1",
      booster: "B12",
      ship: "S30",
      block: "Block 1",
      outcome: "worked",
      headline: "First booster catch",
      tested:
        "Mechazilla caught Super Heavy. No engine failures on the way up. Ship 30 reentered with flap damage and stuck an Indian Ocean splashdown. The flight that proved the chopsticks.",
    },
    {
      flight: 4,
      date: "2024-06-06",
      pad: "OLP-1",
      booster: "B11",
      ship: "S29",
      block: "Block 1",
      outcome: "worked",
      headline: "First soft splashdowns of both stages",
      tested:
        "Booster flew a virtual-tower profile into the Gulf. Ship survived a chewed-up flap and landed in the Indian Ocean, about 6 km off the bullseye. First time both stages came home under control.",
    },
    {
      flight: 3,
      date: "2024-03-14",
      pad: "OLP-1",
      booster: "B10",
      ship: "S28",
      block: "Block 1",
      outcome: "partial",
      headline: "Reached space — neither stage came home",
      tested:
        "First Starship to space. Payload-bay door and a propellant-transfer demo ran. In-space relight and a hard splashdown did not. Booster lost on the landing burn; ship tumbled and died on reentry.",
    },
    {
      flight: 2,
      date: "2023-11-18",
      pad: "OLP-1",
      booster: "B9",
      ship: "S25",
      block: "Block 1",
      outcome: "failed",
      headline: "Hot-stage worked. Both vehicles did not.",
      tested:
        "First hot-staging and first water deluge on the mount. All 33 lit to staging, then the booster failed on boostback. The ship flew until a fire killed comms and the flight-termination system took it.",
    },
    {
      flight: 1,
      date: "2023-04-20",
      pad: "OLP-1",
      booster: "B7",
      ship: "S24",
      block: "Block 1",
      outcome: "failed",
      headline: "First stack. Cleared the pad. Wrecked it.",
      tested:
        "First integrated Super Heavy and Ship. Engines dropped, the stack spun, and the flight-termination system was late. SpaceX called clearing the mount a success. The mount, the tank farm, and a nearby car disagreed.",
    },
  ],
};
