window.TESLA_UPDATES = {
  updated: "2026-10-09",
  note:
    "Plain-English reading of Tesla’s public release notes, merged with a Teslascope snapshot of which builds connected cars are actually reporting. Not Tesla’s official rollout list. A feature can be in the notes and still missing in your country, on your hardware, or on your software package.",
  fsdNow: {
    headline: "FSD right now",
    lines: [
      "North America, HW4 / AI4: FSD Supervised v14.3.11 on 2026.33.5. Automatic Collision Evasion is in this build — US and Canada only.",
      "North America, HW3: FSD Supervised v14.3 Lite on the same 2026.33.5 branch. Parking, unparking and start-from-park. No Collision Evasion.",
      "Europe: FSD Supervised v14.2.2.6 on 2026.33.100. Seen so far in the Netherlands, Belgium, Czechia, Denmark, Estonia, Lithuania, Slovakia and Slovenia — not Ireland yet.",
      "The US FSD stack is ahead. Europe waits on approvals. That is why a car in Dublin can offer 2026.32.7 while a car in California is already on 14.3.11.",
    ],
  },
  countries: [
    { code: "US", name: "United States", aliases: ["usa", "america"] },
    { code: "CA", name: "Canada", aliases: [] },
    { code: "GB", name: "United Kingdom", aliases: ["uk", "britain", "england"] },
    { code: "IE", name: "Ireland", aliases: ["eire"] },
    { code: "DE", name: "Germany", aliases: [] },
    { code: "FR", name: "France", aliases: [] },
    { code: "NL", name: "Netherlands", aliases: ["holland"] },
    { code: "BE", name: "Belgium", aliases: [] },
    { code: "IT", name: "Italy", aliases: [] },
    { code: "ES", name: "Spain", aliases: [] },
    { code: "PT", name: "Portugal", aliases: [] },
    { code: "AT", name: "Austria", aliases: [] },
    { code: "CH", name: "Switzerland", aliases: [] },
    { code: "DK", name: "Denmark", aliases: [] },
    { code: "NO", name: "Norway", aliases: [] },
    { code: "SE", name: "Sweden", aliases: [] },
    { code: "FI", name: "Finland", aliases: [] },
    { code: "PL", name: "Poland", aliases: [] },
    { code: "CZ", name: "Czechia", aliases: ["czech"] },
    { code: "SK", name: "Slovakia", aliases: [] },
    { code: "SI", name: "Slovenia", aliases: [] },
    { code: "HR", name: "Croatia", aliases: [] },
    { code: "HU", name: "Hungary", aliases: [] },
    { code: "GR", name: "Greece", aliases: [] },
    { code: "LT", name: "Lithuania", aliases: [] },
    { code: "EE", name: "Estonia", aliases: [] },
    { code: "AU", name: "Australia", aliases: [] },
    { code: "NZ", name: "New Zealand", aliases: [] },
    { code: "TW", name: "Taiwan", aliases: [] },
    { code: "HK", name: "Hong Kong", aliases: [] },
    { code: "SG", name: "Singapore", aliases: [] },
    { code: "MY", name: "Malaysia", aliases: [] },
    { code: "TH", name: "Thailand", aliases: [] },
    { code: "PH", name: "Philippines", aliases: [] },
    { code: "AE", name: "United Arab Emirates", aliases: ["uae"] },
    { code: "QA", name: "Qatar", aliases: [] },
    { code: "IL", name: "Israel", aliases: [] },
    { code: "TR", name: "Turkey", aliases: [] },
    { code: "MA", name: "Morocco", aliases: [] },
    { code: "CO", name: "Colombia", aliases: [] },
    { code: "UA", name: "Ukraine", aliases: [] },
  ],
  versions: [
    {
      id: "2026.38.3.1",
      family: "2026.38",
      date: "2026-10-07",
      kind: "cabin",
      status: "early",
      headline: "Supercharger maps and a sharper park scene",
      summary:
        "Latest point on the 2026.38 cabin branch. Same features as 2026.38, now in a wider early wave across the US and Europe. No new FSD in this build.",
      features: [
        "Tap View Site Map at some Superchargers: stall layout plus which stalls are free, taken or down.",
        "Higher-quality car image and park scene on the centre display (Model 3 / Y, AMD / HW3).",
        "Dynamic headlight leveling on some Model 3 and Cybertruck cars — low beams aim with traffic so you see more and glare less.",
        "Security fixes.",
      ],
      fsd: null,
      reached:
        "Early wave. Seen in the US, UK, Germany, France, Italy, Austria, Switzerland, the Netherlands and a handful of other European countries. Ireland not reported yet.",
      countries: ["US", "GB", "DE", "FR", "IT", "AT", "CH", "NL", "BE", "ES", "CZ", "PL", "DK", "NO", "TW", "IL", "UA", "MA", "TR"],
    },
    {
      id: "2026.33.5",
      family: "2026.33",
      date: "2026-10-06",
      kind: "fsd",
      status: "rolling",
      headline: "FSD v14.3.11 — North America only",
      summary:
        "The current US / Canada FSD branch. HW4 gets v14.3.11. HW3 gets v14.3 Lite. Europe does not get this build — the EU number is 2026.33.100, and it is still on 14.2.",
      features: [
        "HW4: v14.3.11 — faster reactions, better rare-scene vision, cleaner parking pins, better emergency-vehicle and yellow-light behaviour.",
        "Automatic Collision Evasion (HW4, North America): if you look away or FSD drops unintentionally, the car can re-engage Supervised FSD to try to stay out of a crash.",
        "HW3: v14.3 Lite — distilled from the HW4 model. Parking, unparking, reversing, start-from-park, Arrival Options and Speed Profiles including Sloth.",
        "Cybertruck + Powerwall: Vehicle-to-Home can stretch backup power during an outage.",
        "Also carries the 2026.32 cabin items (Apple Music library, extra wheel visuals) for cars jumping branches.",
      ],
      fsd: "v14.3.11 (HW4) · v14.3 Lite (HW3) · North America",
      reached:
        "Rolling in the United States and Canada only. About 2–3% of the tracked fleet. Not an Irish or UK build.",
      countries: ["US", "CA"],
    },
    {
      id: "2026.33.100",
      family: "2026.33",
      date: "2026-10-06",
      kind: "fsd",
      status: "rolling",
      headline: "Europe’s FSD build — still 14.2",
      summary:
        "Same week as the US 14.3.11 drop, Europe got a 2026.33 build that keeps FSD Supervised on v14.2.2.6. That is the gap in one number: 14.3 in California, 14.2 in the EU, and Ireland has not been seen on this file yet.",
      features: [
        "FSD Supervised v14.2.2.6 for countries that have recognised the Dutch approval.",
        "EU recall remedy 2026_103555 (UNECE R135) on Model 3 / Y — no service visit.",
        "Apple Music library and the usual security fixes on cars that skipped 2026.32.",
      ],
      fsd: "v14.2.2.6 · Europe",
      reached:
        "Early European wave: Netherlands, Belgium, Czechia, Denmark, Estonia, Lithuania, Slovakia, Slovenia. Ireland and the UK not reported on this build as of 9 October.",
      countries: ["NL", "BE", "CZ", "DK", "EE", "LT", "SK", "SI"],
    },
    {
      id: "2026.32.7",
      family: "2026.32",
      date: "2026-09-22",
      kind: "cabin",
      status: "wide",
      headline: "The build most cars are being offered",
      summary:
        "Widest 2026.32 point release. This is the one a lot of European cars — including Ireland — are actually seeing when the screen says an update is ready. Cabin and security, not a new FSD stack.",
      features: [
        "Apple Music: Search → Apple Music → Library for your own songs and playlists.",
        "More wheel options on the on-screen car.",
        "Ad blocker in the in-car browser — useful on older Intel units.",
        "EU recall remedy 2026_103555 on Model 3 / Y.",
        "Security fixes. 2026.32.7 itself is mostly minor fixes on top of 2026.32.3.",
      ],
      fsd: null,
      reached:
        "Wide. Seen across North America, Europe (Ireland included), the Middle East and parts of Asia. Still one of the largest slices of the fleet.",
      countries: [
        "US", "CA", "GB", "IE", "DE", "FR", "NL", "BE", "IT", "ES", "PT", "AT", "CH", "DK", "NO", "SE",
        "FI", "PL", "CZ", "SK", "HR", "HU", "GR", "AE", "IL", "TR", "SG", "HK", "MY", "TH", "CO", "UA", "QA",
      ],
    },
    {
      id: "2026.32.3",
      family: "2026.32",
      date: "2026-09-09",
      kind: "cabin",
      status: "wide",
      headline: "First 2026.32 — wheels, Apple Music, EU recall",
      summary:
        "The notes everyone quotes for 2026.32 landed here. Later .7 cars get the same features plus minor fixes. If your car offers 2026.32.3, this is the list.",
      features: [
        "New wheel visuals on the car in the display.",
        "Apple Music library search.",
        "EU recall 2026_103555 remedy (Model 3 / Y).",
        "Security fixes.",
        "In-car browser ad blocker (also called out on later 2026.32.100).",
      ],
      fsd: null,
      reached:
        "Still on a slice of the fleet in North America, Europe, Australia and Asia. Many cars have already moved on to 2026.32.7.",
      countries: [
        "US", "CA", "GB", "IE", "DE", "FR", "NL", "BE", "IT", "ES", "AU", "TW", "IL", "TR", "QA", "MY",
        "TH", "AE", "SG", "PH", "HK", "CO",
      ],
    },
    {
      id: "2026.27.11",
      family: "2026.27",
      date: "2026-09-22",
      kind: "fsd",
      status: "wide",
      headline: "Still the big North America FSD file",
      summary:
        "A large share of US cars are still here: FSD v14.3.10 on HW4 and v14.2 Lite on HW3. If a US car says 2026.27.11 is ready, this is the FSD step before 14.3.11.",
      features: [
        "HW4: FSD Supervised v14.3.10 — same 14.3 family as 14.3.11, one point behind.",
        "HW3: FSD Supervised v14.2 Lite.",
        "Start from Park, Arrival Options (parking lot / street / driveway) and Speed Profiles, including Sloth.",
      ],
      fsd: "v14.3.10 (HW4) · v14.2 Lite (HW3) · North America",
      reached:
        "Wide in the United States and Canada. Roughly a quarter of the tracked fleet as of early October. Not a European branch.",
      countries: ["US", "CA"],
    },
    {
      id: "2026.27.300",
      family: "2026.27",
      date: "2026-09-15",
      kind: "fsd",
      status: "rolling",
      headline: "Europe’s previous FSD file",
      summary:
        "The European 2026.27 FSD branch, still on v14.2.2.6. Cars in the first 2026.33.100 countries are leaving this one. Ireland may still be offered 2026.32 cabin builds instead.",
      features: [
        "FSD Supervised v14.2.2.6 for approved EU countries.",
        "Cabin carry-overs from the 2026.27 line.",
      ],
      fsd: "v14.2.2.6 · Europe",
      reached:
        "European FSD cars — Netherlands, Belgium and neighbours — before 2026.33.100. Small remaining share.",
      countries: ["NL", "BE", "DE", "DK", "CZ", "EE", "LT", "SI"],
    },
    {
      id: "2026.26.6.3",
      family: "2026.26",
      date: "2026-09-22",
      kind: "cabin",
      status: "limited",
      headline: "Australia and New Zealand branch",
      summary:
        "Oceania is often on its own point release. Same season as 2026.32 elsewhere, different number on the screen.",
      features: [
        "Regional 2026.26 point for Australia and New Zealand.",
        "Cabin and security items from the late-August / September line — not the US 14.3.11 FSD stack.",
      ],
      fsd: null,
      reached: "Australia and New Zealand. Not used in Europe or North America.",
      countries: ["AU", "NZ"],
    },
  ],
};
